### ISSUE TITLE
Alignment issues

### ISSUE THREAD

**Issue by derrgoo** [heppen-dev/skin.blue.twilight#12]
On blue twilight and setting up movie hub I seem to get alignment issues.

It seems there is a bug when you switch to load movies hub first. 

Also, is it possible to increase the poster size for the widget. If easy change maybe you can show me section and I can try. Great skin. Very innovative design. 

![image](https://user-images.githubusercontent.com/63697905/163095805-816a0743-2d80-4bc3-8697-23564ece7149.jpeg)

**Comment by heppen-dev** [comment]
Hey,
Thanks for report. I will look into it in free time :)

**Comment by derrgoo** [comment]
I forgot to ask :-) is it possible to and CLEARART/clear logo on OSD line. I see you already pull CLEARART. Thanks. ![image](https://user-images.githubusercontent.com/63697905/163127993-1c2fabff-2a7c-4059-9520-7fa3b15a4360.jpeg)

**Comment by derrgoo** [comment]
> Hey,
> 
> Thanks for report. I will look into it in free time :)

Interesting - it works on my shield with no issues, so it must only be doing this on my Mac. 👍

**Comment by heppen-dev** [comment]
> > Hey,
> > Thanks for report. I will look into it in free time :)
> 
> Interesting - it works on my shield with no issues, so it must only be doing this on my Mac. +1

Maybe because of different resolution than 1080p or different aspect ratio. I'm not sure. If it works I'm glad.
I don't have Mac to test this unfortunately so I'm gonna close this issue then.
