### ISSUE TITLE
Shadow for osd system time 

### ISSUE THREAD

**Issue by IG2022** [heppen-dev/skin.blue.twilight#6]
Hi Heppen, thanks for the recent update the skin looks alot more refined and works really well. I just wanted to ask if you could consider putting a shadow behind the system time on the osd. It's sometimes very difficult to see especially when there is a scene with a bright background. I know your busy but just wanted to see if you could put that in if you are able. Thanks! 

Here is a picture of what i am talking about. 

![PXL_20220323_041640224 MP](https://user-images.githubusercontent.com/78256798/159623262-50c19909-849c-4518-84cc-8f3e94c3707b.jpg)

**Comment by heppen-dev** [comment]
Yeah, sure. I think I can do this :) Thanks for your idea!

**Comment by IG2022** [comment]
> Yeah, sure. I think I can do this :) Thanks for your idea!

Thanks alot! I really appreciate it!

**Comment by IG2022** [comment]
Ohh and I also wanted to ask you about the system time on the home screen I see it everywhere else but not on the home screen. I'm not sure it that's a bug with my setup or something you just have not put in?

**Comment by heppen-dev** [comment]
> > Yeah, sure. I think I can do this :) Thanks for your idea!
> 
> Thanks alot! I really appreciate it!

https://imgur.com/voRAZkT
It should be better visible now. Maybe in the future I will think about improving it a bit :)

**Comment by heppen-dev** [comment]
> Ohh and I also wanted to ask you about the system time on the home screen I see it everywhere else but not on the home screen. I'm not sure it that's a bug with my setup or something you just have not put in?

Please open another ticket. Screenshot would be appreciated :)

**Comment by IG2022** [comment]
> > > Yeah, sure. I think I can do this :) Thanks for your idea!
> > 
> > 
> > Thanks alot! I really appreciate it!
> 
> https://imgur.com/voRAZkT It should be better visible now. Maybe in the future I will think about improving it a bit :)

Perfect! Thanks! I will open another issue about that system time on the home screen, Thanks for being so responsive.
