### ISSUE TITLE
System time on home screen 

### ISSUE THREAD

**Issue by IG2022** [heppen-dev/skin.blue.twilight#7]
Hi again Heppen, Just wanted to show you what I meant about the system time on the home screen. Ive attached a few screen shots. As you can see the system time is at the top right when not on the home screen but when I go to the home screen it isn't there.  Take a look when you have some time. 

Thanks

<img width="1280" alt="Screen Shot 2022-03-23 at 18 38 41" src="https://user-images.githubusercontent.com/78256798/159671005-83862031-056e-4ace-8840-4323557ce43f.png">

<img width="1280" alt="Screen Shot 2022-03-23 at 18 38 18" src="https://user-images.githubusercontent.com/78256798/159670996-54b1d6bd-0b4b-47b7-a39a-32c8188862f4.png">
!

**Comment by heppen-dev** [comment]
Yeah, after changes to main menu bar I think system time can fit somewhere in the corner :)

**Comment by IG2022** [comment]
> Yeah, after changes to main menu bar I think system time can fit somewhere in the corner :)

Perfect! Looking forward to seeing that change. :) Thanks again!

**Comment by heppen-dev** [comment]
Just added TopBar to home screen and movies hub as well: https://github.com/heppen-dev/skin.blue.twilight/commit/9ac391b44436572a768470a3f734029ad2a461d2
